# Generated by Django 5.2.2 on 2025-08-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0002_creature'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunting_place',
            name='recommended_vocation',
            field=models.ForeignKey(blank=True, help_text='Best vocation for this hunting place', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TibiaGGapi.vocation'),
        ),
    ]
