# Generated by Django 5.2.2 on 2025-08-05 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0003_hunting_place_recommended_vocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunting_place',
            name='comment',
        ),
        migrations.AddField(
            model_name='hunting_place',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the hunting place', null=True),
        ),
        migrations.AddField(
            model_name='hunting_place',
            name='name',
            field=models.CharField(default='Unnamed Hunting Place', help_text='Name of the hunting place', max_length=200),
        ),
        migrations.CreateModel(
            name='Hunting_Place_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='User comment about the hunting place')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hunting_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='TibiaGGapi.hunting_place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_place_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hunting Place Comment',
                'verbose_name_plural': 'Hunting Place Comments',
                'db_table': 'hunting_place_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
