# Generated by Django 5.2.2 on 2025-08-05 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0004_remove_hunting_place_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunting_place',
            name='name',
        ),
    ]
