# Generated by Django 5.2.2 on 2025-08-08 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0005_remove_hunting_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunting_place',
            name='creature',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='TibiaGGapi.creature'),
        ),
    ]
