# Generated by Django 5.2.2 on 2025-08-08 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0006_hunting_place_creature'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hunting_place',
            name='creature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TibiaGGapi.creature'),
        ),
    ]
