# Generated by Django 5.2.2 on 2025-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0007_creature_image_url_alter_hunting_place_creature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunting_place',
            name='creature',
        ),
        migrations.AddField(
            model_name='hunting_place',
            name='creatures',
            field=models.ManyToManyField(help_text='Creatures found in this hunting place', related_name='hunting_places', to='TibiaGGapi.creature'),
        ),
    ]
