# Generated by Django 5.2.2 on 2025-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0008_remove_hunting_place_creature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocation',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
