# Generated by Django 5.2.2 on 2025-08-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0009_vocation_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imbue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Imbue',
                'verbose_name_plural': 'Imbues',
                'db_table': 'imbue',
            },
        ),
        migrations.AddField(
            model_name='hunting_place',
            name='imbues',
            field=models.ManyToManyField(blank=True, help_text='Recommended imbues for this hunting place', related_name='hunting_places', to='TibiaGGapi.imbue'),
        ),
    ]
