# Generated by Django 5.2.2 on 2025-08-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0010_imbue_hunting_place_imbues'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
