# Generated by Django 5.2.2 on 2025-08-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0011_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunting_place',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Items that drop in this hunting place', related_name='hunting_places', to='TibiaGGapi.item'),
        ),
    ]
