# Generated by Django 5.2.2 on 2025-08-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0012_hunting_place_items'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
