# Generated by Django 5.2.2 on 2025-08-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0014_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imbue',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
