# Generated by Django 5.2.2 on 2025-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0015_alter_imbue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunting_place',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for this hunting place', null=True),
        ),
    ]
