# Generated by Django 5.2.2 on 2025-08-20 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TibiaGGapi', '0016_hunting_place_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('min_level', models.IntegerField(blank=True, null=True)),
                ('rec_level', models.IntegerField(blank=True, null=True)),
                ('quest_type', models.CharField(default='main', max_length=50)),
                ('difficulty_rating', models.IntegerField(blank=True, null=True)),
                ('estimated_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('npc_start', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('reward_type', models.CharField(choices=[('experience', 'Experience Points'), ('money', 'Gold Coins'), ('item', 'Item'), ('access', 'Access/Permission'), ('service', 'Service/Feature'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['reward_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QuestDanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creature_name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dangers', to='TibiaGGapi.quest')),
            ],
            options={
                'ordering': ['quest', 'creature_name'],
            },
        ),
        migrations.CreateModel(
            name='QuestMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('objective', models.TextField()),
                ('mission_order', models.IntegerField()),
                ('steps', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('required_items', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dangers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='TibiaGGapi.quest')),
            ],
            options={
                'ordering': ['quest', 'mission_order'],
            },
        ),
        migrations.CreateModel(
            name='QuestQuestReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_order', models.IntegerField(default=0)),
                ('is_final_reward', models.BooleanField(default=False)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TibiaGGapi.questmission')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_rewards', to='TibiaGGapi.quest')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TibiaGGapi.questreward')),
            ],
            options={
                'ordering': ['quest', 'reward_order'],
                'unique_together': {('quest', 'reward', 'mission')},
            },
        ),
    ]
